browser:
  args:
    - --disable-component-update
    - --no-sandbox
    - --disable-dev-shm-usage
    - --disable-webgl
    - --disable-blink-features=AutomationControlled
    - --disable-infobars
  headless: false
  ignore_default_args:
    - --disable-extensions
    - --enable-automation
  user_data_dir: ./profile
extensions:
  paths:
    - C:\Users\Taufik Hidayat\Project\Marathon_Tools\refator-scrape\Extensions\Adguard
    - C:\Users\Taufik Hidayat\Project\Marathon_Tools\refator-scrape\Extensions\uBlock
logging:
  datefmt: "%Y-%m-%d %H:%M:%S"
  format: "%(asctime)s - %(levelname)-4s - %(message)s"
  level: INFO
  log_dir: logs
pixeldrain:
  bypass_urls:
    - https://cdn.pd1.workers.dev/api/file/CODE-FILE
    - https://cdn.pd6.workers.dev/api/file/CODE-FILE
    - https://cdn.pd7.workers.dev/api/file/CODE-FILE
    - https://cdn.pd8.workers.dev/api/file/CODE-FILE
    - https://cdn.pd10.workers.dev/api/file/CODE-FILE
    - https://cdn.pd3-gamedriveorg.workers.dev/api/file/CODE-FILE
    - https://cdn.pd5-gamedriveorg.workers.dev/api/file/CODE-FILE
    - https://cdn.pd9-gamedriveorg.workers.dev/api/file/CODE-FILE
providers:
  send_aliases:
    - send.
    - sendnow
    - sendnow.
    - send.cw
    - send.now
    - send.com
target_url: https://filecrypt.co/Container/5416F3621D.html
timeouts:
  batch_delay: 1
  captcha_check: 5
  page_load: 10000
  password_check: 5
  popup: 10000
  selector_wait: 10000
user_agents:
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/134.0.0.0 Safari/537.36
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
